-- 1. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS Customers (
    CustomerId INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS Products (
    ProductId INTEGER PRIMARY KEY AUTOINCREMENT,
    SKU TEXT NOT NULL UNIQUE,
    Name TEXT NOT NULL,
    Description TEXT NULL,
    Price DECIMAL(18, 2) NOT NULL CHECK (Price >= 0),
    IsActive INTEGER NOT NULL DEFAULT 1,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. INVENTORIES TABLE
CREATE TABLE IF NOT EXISTS Inventories (
    ProductId INTEGER PRIMARY KEY,
    Quantity INTEGER NOT NULL CHECK (Quantity >= 0),
    RowVersion BLOB NOT NULL,
    FOREIGN KEY (ProductId) REFERENCES Products (ProductId) ON DELETE CASCADE
);

-- 4. ORDERS TABLE
CREATE TABLE IF NOT EXISTS Orders (
    OrderId INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerId INTEGER NOT NULL,
    OrderDate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Status TEXT NOT NULL DEFAULT 'Pending',
    TotalAmount DECIMAL(18, 2) NOT NULL DEFAULT 0.00 CHECK (TotalAmount >= 0),
    FOREIGN KEY (CustomerId) REFERENCES Customers (CustomerId) ON DELETE RESTRICT
);

-- 5. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS OrderItems (
    OrderId INTEGER NOT NULL,
    ProductId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(18, 2) NOT NULL CHECK (UnitPrice >= 0),
    PRIMARY KEY (OrderId, ProductId),
    FOREIGN KEY (OrderId) REFERENCES Orders (OrderId) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES Products (ProductId)
);

-- INDEXES
CREATE INDEX IF NOT EXISTS IX_Orders_CustomerId ON Orders(CustomerId);
CREATE INDEX IF NOT EXISTS IX_Products_IsActive ON Products(IsActive);